### ISSUE TITLE
Confidence intervals for low prevalence categories

### ISSUE THREAD

**Issue by omstuhler** [naoki-egami/dsl#3]
I'm interested in estimating category proportions across groups. My categories have low prevalence, so that in some groups, the confidence intervals derived from the linear model overlap with 0. I'm therefore using the logit model and correct the estimates and CIs to probabilities post-analysis, leading to the same estimates but asymmetrical CIs that don't overlap with 0. Along the lines of:

```r
data("data_time")
out_time <- dsl(model = "logit",
                formula = Y ~ as.factor(year) - 1,
                predicted_var = "Y",
                prediction = "pred_Y",
                data = data_time)
results <- summary(out_time)

logit_to_prob <- function(logit_value){
  return(1 / (1 + exp(-logit_value)))
}
results$Estimate = logit_to_prob(results$Estimate )
results$`CI Lower` = logit_to_prob(results$`CI Lower`)
results$`CI Upper` = logit_to_prob(results$`CI Upper`)
```
In your tutorial, you write that

> To estimate the category proportions over time, researchers can regress a text category on time using linear regression without an intercept. [...] Note that this estimation approach uses the numerical equivalence between linear regression (lm) and subgroup means (as scholars use linear regression to compute difference-in-means in randomized experiments), and thus, researchers do not need to use logistic regression (logit).

To confirm: is the above the way to go, or is there a reason why you're discouraging the use of the logistic model other than the inconvenience of having to convert the estimates?

**Comment by naoki-egami** [comment]
Thank you for the question! When you only include `as.factor(year)`, whether you use the linear model or the logit model (with proper post-calculation of the mean prob) should not matter in a large sample size. We recommend the `lm` approach because it is simpler. This also means getting slightly smaller confidence intervals under the logit model is probably a statistical coincidence. It is difficult to justify the logit model over the lm model from a statistical perspective. 

If you are concerned that your confidence intervals are too large to distinguish substantively important effect sizes, we recommend increasing the number of expert annotations. This can transparently reduce standard errors and narrow your confidence intervals. 

Please let us know if you have any further questions!

**Comment by omstuhler** [comment]
Thank you for the response. Maybe my code example was confusing. My point was merely that a linear model can, unsurprisingly, give CI's < 0 or > 1 for very low or very high category prevalences within a group (which many researchers will be dealing with). E.g., if we take out some of the 0 cases in your data and increase the category prevalence to around 88%, we'll get:

```r
data("data_time")
data_time_inflated = data_time[-sample(which(data_time$Y == 0), 200),]
out_time <- dsl(model = "lm",
                formula = Y ~ as.factor(year) - 1,
                predicted_var = "Y",
                prediction = "pred_Y",
                data = data_time_inflated)
results <- summary(out_time)
results$`CI Upper`
[1] 1.0003 1.0286 0.8573 0.9117 1.0547 0.9614 1.0612 1.0527 0.9903 0.9532
```
I understand that one way to deal with this would be to annotate more cases. However, assuming I'm generally okay with the sizes of the CIs as long as they don't take on values < 0 or > 1, it seems to make sense to take the logit model and convert CIs back to probabilities:

```r
out_time <- dsl(model = "logit",
                formula = Y ~ as.factor(year) - 1,
                predicted_var = "Y",
                prediction = "pred_Y",
                data = data_time_inflated)
results <- summary(out_time)
logit_to_prob <- function(logit_value){
  return(1 / (1 + exp(-logit_value)))
}
results$`CI Upper` = logit_to_prob(results$`CI Upper`)
results$`CI Upper`
[1] 0.9583695 0.9930158 0.8246970 0.8775144 0.9996919 0.9237483 0.9999503 0.9995215 0.9614505 0.9177378
```
I only wanted to confirm that there is no dsl-inherent reason why one shouldn't use this model when deriving category prevalences and CIs, given what you had written in the tutorial.

**Comment by naoki-egami** [comment]
Ah, I see. This is a great point. Yes, there is no dsl-inherent reason why one shouldn't use the logit model when deriving category prevalences and CIs.
