### ISSUE TITLE
Getting dsl estimates for entire corpus

### ISSUE THREAD

**Issue by omstuhler** [naoki-egami/dsl#4]
What's the proper way to get the ```dsl``` estimate and corresponding CIs for an entire corpus? I was assuming that I could do this by just taking the intercept of a null model. For instance, say my corpus only consists of observations in the year 2001, I would fit:
```r
data_time_subset_2 = subset(data_time, data_time$year %in% c(2001))
out_time <- dsl(model = "lm",
                formula = Y ~ 1,
                predicted_var = "Y",
                prediction = "pred_Y",
                data = data_time_subset_2)
summary(out_time)

# Estimate Std. Error CI Lower CI Upper p value    
# 0.6523     0.0735   0.5081   0.7964       0 ***
```

However, I notice that these estimates are slightly different from what I get if I fit a model with more observations. E.g., if I design my corpus to consist only of observations from the years 2001 and 2002 and use a factor variable, I get the following:
```r
data("data_time")
data_time_subset_1 = subset(data_time, data_time$year %in% c(2001, 2002))
out_time <- dsl(model = "lm",
                formula = Y ~ as.factor(year) - 1,
                predicted_var = "Y",
                prediction = "pred_Y",
                data = data_time_subset)

summary(out_time)
#                      Estimate Std. Error CI Lower CI Upper p value    
#as.factor(year)2001   0.6564     0.0741   0.5113   0.8016       0 ***
#as.factor(year)2002   0.6282     0.0715   0.4882   0.7683       0 ***
```

As you can see, the estimates for observations in the year 2001 are slightly different. Can these differences be safely ignored? The background of my question is that I would like to estimate a moving average and get a dsl estimate for specific time windows in my data.

**Comment by naoki-egami** [comment]
@omstuhler Thank you for your question. Yes, this difference comes from small randomness in the cross-fitting step behind it (conceptually a bit similar to the randomness you get when you use Bootstrap, for example). If you want to stabilize it more, if you can change argument `sample_split` and probably make it `sample_split = 100`, I think it will take a longer time, but the difference due to randomness will be smaller.
